# 10271
# nohup python -m torch.distributed.launch --nproc_per_node=4 --master_port 49104  fusion_main.py --exp_config exp_config/CVC14/exp_6.yaml --output_dir /data/wangsong/results/CVC14/exp6 --action train > ../DAB-DETR-nohup/ms-detr/CVC14_6_nohup &
# python fusion_main.py --output_dir /data/wangsong/results/CVC14/exp6 --action test --resume /data/wangsong/results/CVC14/exp6/checkpoint.pth --exp_config exp_config/CVC14/exp_6.yaml --visible_devices 2
TRAIN:
  lr_backbone: 1e-4
  epochs: 10
  lr_drop: [5, ]
  save_checkpoint_interval: 1
TEST:
  metric: 'cvc14'

MODEL:
  BACKBONE:
    backbone_share: False
    FEATURE_FUSION:
      fusion_flag: True
      only_fusion: True
  MS_DETR:
    use_dab: False
    num_feature_levels: 4
    num_queries: 300
    content_embedding: False
    rgb_branch: False
    t_branch: False
  TRANSFORMER:
    fusion_backbone_encoder: False
    dim_feedforward: 1024
    num_feature_levels: 4
    ENCODER:
      layers_rgb: 0
      layers_t: 0
      layers_share: 0
      layers_fusion: 6
      pre_norm: False
    DECODER:
      pre_norm: False
      use_region_ca: False
      fusion: False
  LOSS:
    instance_reweight: False

DATASET:
  batch_size: 1
  format: 'cvc14'
  KAIST:
    root_dirs_train: ['/data/wangsong/datasets/CVC-14', ]
    root_dirs_test: ['/data/wangsong/datasets/CVC-14', ]
    rgb_datasets_train: ['train_cvc14_visible', ]
    t_datasets_train: ['train_cvc14_fir', ]
    rgb_datasets_test: ['test_cvc14_visible', ]
    t_datasets_test: ['test_cvc14_fir', ]
  TRANSFORMS:
    img_size: (471, 640)
    mosaic_flag: False
    mix_up_flag: False
    random_affine_flag: False
    RANDAUGMENT:
      flag: False
      aug_space: 'color'
      num: 2
      level: 10
      random: True

EXPERIMENT:
  fit_flag: True
  pretrain_model_path: '/data/wangsong/results/23_5_25/exp46/checkpoint.pth'